name: Actualisation des Matchs

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Lancer le scraper
        run: |
          python scraper.py

      - name: Commit et Push automatique
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mise à jour automatique des matchs"
          file_pattern: "matches.json"
